In [1]:
import numpy as np
import pandas as pd

## Bring the voteview data and filter to the 118th congress

In [2]:
ideology = pd.read_csv("https://voteview.com/static/data/out/members/HS118_members.csv")

In [3]:
ideology["chamber"].value_counts()

chamber
House     442
Senate    101
Name: count, dtype: int64

In [4]:
ideology[["bioname",'chamber','party_code','district_code','state_abbrev','nominate_dim1']]\
.sort_values("nominate_dim1",ascending=True, ignore_index = True)


# ['bioname'].sort_values['nominate_dim1']

,bioname,chamber,party_code,district_code,state_abbrev,nominate_dim1
0,"GARCIA, Sylvia",House,100,29,TX,-0.792
1,"WARREN, Elizabeth",Senate,100,0,MA,-0.751
2,"LEE, Barbara",House,100,12,CA,-0.677
3,"WATERS, Maxine",House,100,43,CA,-0.656
4,"CASTEN, Sean",House,100,6,IL,-0.652
...,...,...,...,...,...,...
538,"MCCORMICK, Rich",House,200,6,GA,0.870
539,"LEE, Mike",Senate,200,0,UT,0.891
540,"PAUL, Rand",Senate,200,0,KY,0.891
541,"TUBERVILLE, Thomas Hawley (Tommy)",Senate,200,0,AL,0.936
542,"SCHMITT, Eric Stephen",Senate,200,0,MO,0.965

In [5]:
replace_map = {100:'Democrat',200:'Republican',328:"independent"}

ideology['party_code'] = ideology['party_code'].replace(replace_map)
ideology["party_code"].value_counts()

party_code
Republican     274
Democrat       266
independent      3
Name: count, dtype: int64

In [6]:
ideology.query("party_code == 'independent'")[['bioname','chamber','state_abbrev','nominate_dim1']]

                      bioname chamber state_abbrev  nominate_dim1
447           SINEMA, Kyrsten  Senate           AZ         -0.246
479  KING, Angus Stanley, Jr.  Senate           ME         -0.162
532          SANDERS, Bernard  Senate           VT         -0.539

In [7]:
ideology.query("state_abbrev == 'VA' & chamber == 'House'")[['district_code','party_code','bioname']]

     district_code  party_code                      bioname
410              1  Republican           WITTMAN, Robert J.
411             11    Democrat  CONNOLLY, Gerald E. (Gerry)
412              9  Republican          GRIFFITH, H. Morgan
413              8    Democrat   BEYER, Donald Sternoff Jr.
414              6  Republican              CLINE, Benjamin
415              7    Democrat          SPANBERGER, Abigail
416             10    Democrat             WEXTON, Jennifer
417              5  Republican                    GOOD, Bob
418              2  Republican            KIGGANS, Jennifer
419              4    Democrat          MCCLELLAN, Jennifer
420              3    Democrat             SCOTT, Robert C.

In [8]:
votes = pd.read_csv("https://voteview.com/static/data/out/votes/HS118_votes.csv")

In [9]:
votes

        congress chamber  rollnumber  icpsr  cast_code   prob
0            118   House           1  14854          6  100.0
1            118   House           1  14863          6   98.1
2            118   House           1  14873          1  100.0
3            118   House           1  15029          1  100.0
4            118   House           1  15433          1  100.0
...          ...     ...         ...    ...        ...    ...
323858       118  Senate         313  42304          1   90.7
323859       118  Senate         313  42305          1   92.6
323860       118  Senate         313  49308          1   88.6
323861       118  Senate         313  49703          1   98.6
323862       118  Senate         313  91300          1  100.0

[323863 rows x 6 columns]

In [10]:
# first do the merge in a way to checks for problems
ideology_votes = pd.merge(votes,ideology,on = 'icpsr', how = 'outer', validate = 'many_to_one',indicator = 'matched')

In [11]:
ideology_votes = pd.merge(votes,ideology,on = 'icpsr', how = 'inner')

In [12]:
ideology_votes

,congress_x,chamber_x,rollnumber,icpsr,cast_code,prob,congress_y,chamber_y,state_icpsr,district_code,...,died,nominate_dim1,nominate_dim2,nominate_log_likelihood,nominate_geo_mean_probability,nominate_number_of_votes,nominate_number_of_errors,conditional,nokken_poole_dim1,nokken_poole_dim2
0,118,House,1,14854,6,100.0,118,House,51,5,...,NaN,0.334,0.142,-91.32590,0.86116,611,30,NaN,0.360,0.742
1,118,House,2,14854,6,100.0,118,House,51,5,...,NaN,0.334,0.142,-91.32590,0.86116,611,30,NaN,0.360,0.742
2,118,House,3,14854,6,100.0,118,House,51,5,...,NaN,0.334,0.142,-91.32590,0.86116,611,30,NaN,0.360,0.742
3,118,House,4,14854,6,100.0,118,House,51,5,...,NaN,0.334,0.142,-91.32590,0.86116,611,30,NaN,0.360,0.742
4,118,House,5,14854,6,100.0,118,House,51,5,...,NaN,0.334,0.142,-91.32590,0.86116,611,30,NaN,0.360,0.742
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323858,118,Senate,309,42305,1,100.0,118,Senate,71,0,...,NaN,-0.470,-0.085,-0.51644,0.98972,50,0,NaN,-0.527,-0.138
323859,118,Senate,310,42305,6,100.0,118,Senate,71,0,...,NaN,-0.470,-0.085,-0.51644,0.98972,50,0,NaN,-0.527,-0.138
323860,118,Senate,311,42305,6,100.0,118,Senate,71,0,...,NaN,-0.470,-0.085,-0.51644,0.98972,50,0,NaN,-0.527,-0.138
323861,118,Senate,312,42305,1,96.9,118,Senate,71,0,...,NaN,-0.470,-0.085,-0.51644,0.98972,50,0,NaN,-0.527,-0.138
323862,118,Senate,313,42305,1,92.6,118,Senate,71,0,...,NaN,-0.470,-0.085,-0.51644,0.98972,50,0,NaN,-0.527,-0.138