In [1]:
import numpy as np
import pandas as pd

In [30]:
nba = pd.read_csv("nba.csv", low_memory = False)
pd.set_option("display.max_column", 30)
nba.head(6).T

,0,1,2,3,4,5
Unnamed: 0,0,1,2,3,4,5
game_id,202202170BRK,202202170BRK,202202170BRK,202202170BRK,202202170BRK,202202170BRK
game_date,2022-02-17,2022-02-17,2022-02-17,2022-02-17,2022-02-17,2022-02-17
OT,0,0,0,0,0,0
H_A,A,A,A,A,A,A
...,...,...,...,...,...,...
SG%,36.0,0.0,32.0,10.0,0.0,7.0
SF%,60.0,4.0,67.0,0.0,0.0,62.0
PF%,4.0,85.0,0.0,0.0,0.0,31.0
C%,0.0,11.0,0.0,0.0,100.0,0.0
active_position_minutes,46.253586,52.15259,47.021807,27.603314,36.472537,54.944529

In [25]:
## first normal form 

nba = nba.drop(["Inactives"],axis = 1)
nba.head(3).T

                                    0             1             2
Unnamed: 0                          0             1             2
game_id                  202202170BRK  202202170BRK  202202170BRK
game_date                  2022-02-17    2022-02-17    2022-02-17
OT                                  0             0             0
H_A                                 A             A             A
...                               ...           ...           ...
SG%                              36.0           0.0          32.0
SF%                              60.0           4.0          67.0
PF%                               4.0          85.0           0.0
C%                                0.0          11.0           0.0
active_position_minutes     46.253586      52.15259     47.021807

[81 rows x 3 columns]

In [26]:
# second normal form 
# Only have one column for the primary keep it's kinda cheating
players = nba[["player_id","player"]].drop_duplicates()

In [28]:
# third normal form 

nba = nba.drop(["game_date","OT","season"],axis = 1)

In [31]:
nba

,Unnamed: 0,game_id,game_date,OT,H_A,Team_Abbrev,Team_Score,Team_pace,Team_efg_pct,Team_tov_pct,Team_orb_pct,Team_ft_rate,Team_off_rtg,Inactives,Opponent_Abbrev,...,FDP,SDP,DKP_per_minute,FDP_per_minute,SDP_per_minute,pf_per_minute,ts,last_60_minutes_per_game_starting,last_60_minutes_per_game_bench,PG%,SG%,SF%,PF%,C%,active_position_minutes
0,0,202202170BRK,2022-02-17,0,A,WAS,117,94.5,0.627,13.5,22.9,0.157,123.8,"Joel Ayayi, Bradley Beal, Kristaps Porzingis",BRK,...,22.7,24.75,0.730769230769231,0.698461538461538,0.761538461538461,0.061538,9.00,31.716667,22.017778,1.0,36.0,60.0,4.0,0.0,46.253586
1,1,202202170BRK,2022-02-17,0,A,WAS,117,94.5,0.627,13.5,22.9,0.157,123.8,"Joel Ayayi, Bradley Beal, Kristaps Porzingis",BRK,...,16.9,17.25,0.652533039647577,0.558370044052863,0.569933920704846,0.099119,7.44,34.324000,18.475954,0.0,0.0,4.0,85.0,11.0,52.152590
2,2,202202170BRK,2022-02-17,0,A,WAS,117,94.5,0.627,13.5,22.9,0.157,123.8,"Joel Ayayi, Bradley Beal, Kristaps Porzingis",BRK,...,18.0,18.75,0.717562254259502,0.707732634338139,0.737221494102228,0.000000,7.00,29.820290,16.051693,0.0,32.0,67.0,0.0,0.0,47.021807
3,3,202202170BRK,2022-02-17,0,A,WAS,117,94.5,0.627,13.5,22.9,0.157,123.8,"Joel Ayayi, Bradley Beal, Kristaps Porzingis",BRK,...,24.9,25.50,1.13709677419355,1.20483870967742,1.23387096774194,0.048387,7.88,29.920833,14.603922,90.0,10.0,0.0,0.0,0.0,27.603314
4,4,202202170BRK,2022-02-17,0,A,WAS,117,94.5,0.627,13.5,22.9,0.157,123.8,"Joel Ayayi, Bradley Beal, Kristaps Porzingis",BRK,...,27.0,27.25,1.79502369668246,1.91943127962085,1.93720379146919,0.000000,6.88,20.095833,14.538095,0.0,0.0,0.0,0.0,100.0,36.472537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112118,112118,202003070GSW,2020-03-07,0,H,GSW,118,90.9,0.606,7.0,18.9,0.263,129.9,"Stephen Curry, Draymond Green, Alen Smailagic,...",PHI,...,25.8,26.00,0.660971223,0.696043165,0.701438849,0.107914,13.08,33.110667,19.232562,0.0,2.0,77.0,21.0,0.0,57.207786
112119,112119,202003070GSW,2020-03-07,0,H,GSW,118,90.9,0.606,7.0,18.9,0.263,129.9,"Stephen Curry, Draymond Green, Alen Smailagic,...",PHI,...,16.2,16.50,0.595309681,0.584485869,0.595309681,0.036079,6.00,25.470833,20.228571,5.0,45.0,43.0,7.0,0.0,58.202391
112120,112120,202003070GSW,2020-03-07,0,H,GSW,118,90.9,0.606,7.0,18.9,0.263,129.9,"Stephen Curry, Draymond Green, Alen Smailagic,...",PHI,...,15.1,16.25,1.226415094,1.139622642,1.226415094,0.150943,4.00,24.083333,13.228788,0.0,0.0,0.0,9.0,91.0,49.630640
112121,112121,202003070GSW,2020-03-07,0,H,GSW,118,90.9,0.606,7.0,18.9,0.263,129.9,"Stephen Curry, Draymond Green, Alen Smailagic,...",PHI,...,23.7,25.25,0.794025157,0.745283019,0.794025157,0.094340,12.64,34.783333,27.691667,0.0,44.0,48.0,8.0,0.0,58.923515
112122,112122,202003070GSW,2020-03-07,0,H,GSW,118,90.9,0.606,7.0,18.9,0.263,129.9,"Stephen Curry, Draymond Green, Alen Smailagic,...",PHI,...,8.7,8.75,0.569852941,0.639705882,0.643382353,0.000000,2.76,10.415645,6.050000,81.0,19.0,0.0,0.0,0.0,45.958787